[project]
name = "text2audio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.106.1",
    "python-dotenv>=1.1.1",
    "regex>=2025.9.1",
]
